# Generated by Django 5.2.8 on 2025-11-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('rnd', '0005_alter_patent_stat_conference_copyright_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='contactOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('stat', models.CharField(choices=[('Notice', 'Notice'), ('Activity', 'Activity'), ('Meeting', 'Meeting')], max_length=30)),
                ('faculty', models.ManyToManyField(blank=True, null=True, to='rnd.facult')),
            ],
        ),
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('thrustArea', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('stage', models.CharField(blank=True, choices=[('Ideation]', 'Ideation'), ('Validation', 'Validation'), ('Early Traction', 'Early Traction'), ('Scaling', 'Scaling'), ('Maturity', 'Maturity')], max_length=20, null=True)),
                ('stat', models.CharField(blank=True, choices=[('Incubator', 'Incubator'), ('Startup', 'Startup')], max_length=20, null=True)),
                ('contact', models.ManyToManyField(to='base.contactorg')),
            ],
        ),
    ]
