# Generated by Django 5.1.7 on 2025-11-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_achievement_contactorg_event_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='querys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('message', models.TextField()),
                ('subject', models.CharField(choices=[('General Inquiry', 'Gen'), ('IIC Membership', 'Mem'), ('Project Support', 'Ps'), ('Competition Information', 'Competition'), ('Other', 'Other')], max_length=70)),
            ],
        ),
    ]
