# Generated by Django 5.2.8 on 2025-11-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_iicinfo_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="iicinfo",
            name="navLogo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
