# Generated by Django 5.2.8 on 2025-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_activity_gallery_notice_achievement_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, choices=[('IIC Calender Activity', 'Iic Calender'), ('MIC_Driven Activity', 'Mic Driven'), ('Celebration Activity', 'Celebration'), ('Self Driven Activity', 'Self Driven')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
