# Generated by Django 5.2.8 on 2025-12-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_activity_category_alter_activity_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificate/images/"
                    ),
                ),
                (
                    "support",
                    models.FileField(
                        blank=True, null=True, upload_to="certificate/pdfs/"
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="teamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="member/images/"
                    ),
                ),
                (
                    "support",
                    models.FileField(blank=True, null=True, upload_to="member/pdfs/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="achievement",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
