# Generated by Django 5.2.8 on 2025-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_certificate_teammember_achievement_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="incubation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "support",
                    models.FileField(
                        blank=True, null=True, upload_to="incubation/pdfs/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ipr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "support",
                    models.FileField(blank=True, null=True, upload_to="ipr/pdfs/"),
                ),
            ],
        ),
    ]
