# Generated by Django 5.2.8 on 2025-12-08 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_incubation_ipr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="date",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="time",
        ),
    ]
