# Generated by Django 5.2.8 on 2025-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_teammember_support_teammember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='achievement',
            name='stat',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='support',
            field=models.FileField(blank=True, null=True, upload_to='member/pdfs/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, choices=[('IIC Calender Activity', 'Iic Calender'), ('MIC Driven Activity', 'Mic Driven'), ('Celebration Activity', 'Celebration'), ('Self Driven Activity', 'Self Driven')], max_length=25, null=True),
        ),
    ]
