# Generated by Django 5.2.8 on 2025-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_remove_teammember_role_achievement_stat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Convenor", "Convenor"),
                    ("Co-Convenor", "Co Convenor"),
                    ("Convenor of External Affairs", "Convenor External"),
                    (
                        "Hult Prize Campus Director & Operations Head",
                        "Director Operations Head",
                    ),
                    ("Chief Financial & Strategic Advisor", "Chief Financial"),
                    ("Head of Tech Wing", "Head Tech Wing"),
                    ("Co-Head of Tech Wing", "Co Head Tech Wing"),
                    ("Head of Graphics Wing", "Head Graphics Wing"),
                    ("Co-Head of Graphics Wing", "Co Head Graphics Wing"),
                    ("Head of Startup Wing", "Head Startup Wing"),
                    ("Co-Head of Startup Wing", "Co Head Startup Wing"),
                    (
                        "Head of Public Relations And Outreach wing",
                        "Head Pr Outreach Wing",
                    ),
                    (
                        "Co-Head of Public Relations And Outreach wing",
                        "Co Head Pr Outreach Wing",
                    ),
                    ("Head of Management and Resource wing", "Head Management Wing"),
                    (
                        "Co-Head of Management and Resource wing",
                        "Co Head Management Wing",
                    ),
                    ("Head of Social Media Wing", "Head Social Media Wing"),
                    ("Co-Head of Social Media Wing", "Co Head Social Media Wing"),
                    ("Head of Sponsorship Wing", "Head Sponsorship Wing"),
                    ("Co-Head of Sponsorship Wing", "Co Head Sponsorship Wing"),
                    ("Head of Content Wing", "Head Content Wing"),
                    ("Co-Head of Content Wing", "Co Head Content Wing"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
