# Generated by Django 5.2.8 on 2025-12-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_teammember_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-created']},
        ),
    ]
