# Generated by Django 5.2.8 on 2025-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_teammember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="meetings/pdf"),
        ),
    ]
