# Generated by Django 5.2.8 on 2025-12-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_meeting_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="photo",
        ),
        migrations.AddField(
            model_name="meeting",
            name="support",
            field=models.FileField(blank=True, null=True, upload_to="meeting/pdfs/"),
        ),
    ]
