# Generated by Django 5.2.8 on 2025-12-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created']},
        ),
    ]
