# Generated by Django 5.2.8 on 2025-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='support',
            field=models.FileField(blank=True, null=True, upload_to='meeting/pdfs/'),
        ),
    ]
