# Generated by Django 5.2.8 on 2025-12-09 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_remove_meeting_photo_meeting_support"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["-created"]},
        ),
    ]
