# Generated by Django 5.2.8 on 2025-12-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_teammember_facultrole_alter_teammember_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "support",
                    models.FileField(blank=True, null=True, upload_to="idea/pdfs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Approved", "Approved"), ("Pending", "Pending")],
                        default="Approved",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
