# Generated by Django 5.2.8 on 2025-11-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='suff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='facult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.dept')),
                ('suf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.suff')),
            ],
        ),
    ]
