# Generated by Django 5.2.8 on 2025-11-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0002_suff_facult'),
    ]

    operations = [
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patentNumber', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True)),
                ('stat', models.CharField(blank=True, choices=[('Published', 'Published'), ('Granted', 'Granted')], max_length=10, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.facult')),
            ],
        ),
    ]
