# Generated by Django 5.2.8 on 2025-11-11 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0003_patent'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.CharField(blank=True, max_length=1000)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('publisherName', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(blank=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.facult')),
            ],
        ),
        migrations.CreateModel(
            name='bookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.CharField(blank=True, max_length=1000)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('chapterName', models.CharField(blank=True, max_length=300)),
                ('pageNo', models.CharField(blank=True, max_length=50)),
                ('doiLink', models.CharField(blank=True, max_length=500)),
                ('publisherName', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(blank=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.facult')),
            ],
        ),
    ]
