# Generated by Django 5.2.8 on 2025-11-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0004_book_bookchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='stat',
            field=models.CharField(blank=True, choices=[('Published', 'Published'), ('Granted', 'Granted')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.CharField(blank=True, max_length=1000)),
                ('issn', models.CharField(blank=True, max_length=30)),
                ('journalName', models.CharField(blank=True, max_length=200)),
                ('publisherName', models.CharField(blank=True, max_length=200)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('no', models.CharField(blank=True, max_length=20)),
                ('pageNo', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField(blank=True)),
                ('doiLink', models.CharField(blank=True, max_length=500)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.facult')),
            ],
        ),
        migrations.CreateModel(
            name='copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyrightNumber', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True)),
                ('stat', models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Pending', 'Pending'), ('Under Review', 'Reviewing')], max_length=40, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.facult')),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.CharField(blank=True, max_length=1000)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('journalName', models.CharField(blank=True, max_length=200)),
                ('publisherName', models.CharField(blank=True, max_length=200)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('no', models.CharField(blank=True, max_length=20)),
                ('pageNo', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField(blank=True)),
                ('doiLink', models.CharField(blank=True, max_length=500)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.facult')),
            ],
        ),
    ]
