# Generated by Django 5.1.7 on 2025-11-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0005_alter_patent_stat_conference_copyright_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googleScholar', models.CharField(blank=True, max_length=500, null=True)),
                ('orcid', models.CharField(blank=True, max_length=50, null=True)),
                ('scopusid', models.CharField(blank=True, max_length=50, null=True)),
                ('researchid', models.CharField(blank=True, max_length=50, null=True)),
                ('vidwanPortal', models.CharField(blank=True, max_length=500, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnd.facult')),
            ],
        ),
    ]
