# Generated by Django 5.2.8 on 2025-11-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0007_book_support_bookchapter_support_copyright_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facult',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
