# Generated by Django 5.2.8 on 2025-12-05 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0008_facult_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facult',
            name='experience',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='facult',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='facult',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Post Graduate', 'Post Graduate'), ('Doctorate', 'Doctorate')], default='Select', null=True),
        ),
        migrations.AddField(
            model_name='facult',
            name='role',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
