# Generated by Django 5.2.8 on 2025-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0009_facult_experience_facult_phone_facult_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facult',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Post Graduate', 'Post Graduate'), ('Doctorate', 'Doctorate')], null=True),
        ),
    ]
