# Generated by Django 5.2.8 on 2025-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0010_alter_facult_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
